# Netlify configuration explicitly for dist folder
# This file is designed to override other configurations 
# to ensure proper MIME types for HTML files

# Main HTML files need explicit Content-Type
[[headers]]
  for = "/index.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"

# Wildcard rule for all HTML pages (handled by SPA)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# CSS files with proper MIME type
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# JavaScript files with proper MIME type
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# The following redirect rule tells Netlify to redirect all paths to index.html.
# This allows React Router to handle the routing client-side.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {Content-Type = "text/html; charset=utf-8"}